import { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "../components/layout/SessionWrapper"; // Import the new SessionWrapper



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fetch session using getSession inside RootLayout
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body className={``}>
        {/* Wrap the children with SessionWrapper to pass the session */}
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}