import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getSession } from "next-auth/react";
import SessionWrapper from "../components/layout/SessionWrapper"; // Import the new SessionWrapper



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fetch session using getSession inside RootLayout
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const session = await getSession();

  console.log("The session",session)

  return (
    <html lang="en">
      <body className={``}>
        {/* Wrap the children with SessionWrapper to pass the session */}
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}